name: Events Demo 1
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
  workflow_dispatch:

jobs: 
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm install
      - name: Build Code
        run: npm run build
      - name: Deploy
        run: echo "Deploying"
